<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <UserSecretsId>rrhh-api-9c1f4e2a-5b7d-4c3e-8a61-2f0d9e7b4c10</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Scalar.AspNetCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RRHH.Application\RRHH.Application.csproj" />
    <ProjectReference Include="..\RRHH.Infrastructure\RRHH.Infrastructure.csproj" />
  </ItemGroup>

</Project>
