<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <!-- PasswordHasher, autenticación JWT y opciones de ASP.NET Core -->
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
    <PackageReference Include="ClosedXML" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RRHH.Application\RRHH.Application.csproj" />
  </ItemGroup>

</Project>
